version: "3.9"

services:
  app:
    container_name: app
    image: app
    environment:
    - BACKEND_HOST="http://backend:3333"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - network1
    restart: always
    ports:
    - "8080:80"


networks:
  network1:
    external: true
    name: mealer
