version: "3.9"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - network1
    restart: always
    ports:
    - "8080:8080"


networks:
  network1:
    external: true
    name: mealer
