name: backend

on:
  push:
    tags:
    - backend/*

jobs:
  autodeploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          ./backend
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/mealweek-backend
      VITE_API_URL: "https://mealer.fly.dev"
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=match,pattern=backend-(.*),group=1
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
